# Generated by Django 4.2.5 on 2023-10-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blacklistedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackListedToken',
        ),
    ]
