# Generated by Django 2.2.28 on 2023-06-10 09:58

from django.db import migrations, models
from tasks.models import Task
from django.contrib.auth.models import User
import django.db.models.deletion
from django.conf import settings
from django.contrib.auth.models import User as user

def set_owner(apps, schema_editor):
    user = User.objects.get(username = 'jack')
    tasks = Task.objects.all()
    for task in tasks:
        task.owner = user
        task.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.User', null=True),
        ),
        migrations.RunPython(set_owner),
    ]
